# Generated by Django 4.0.4 on 2022-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcloudauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authfileupload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
